version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/deploy
hooks:
  AfterInstall:
    - location: scripts/install_deps
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
