#!/bin/sh

BIN_PATH=/home/ec2-user/swebapp/swebapp
LOG_PATH=/home/ec2-user/swebapp/swebapp.log

rm -f $LOG_PATH

function BuildApp {
    cd /home/ec2-user/swebapp
    echo "Building Application" >> $LOG_PATH
    go mod tidy 
    if [ -z $? ]; then
      echo "Go Tidy Succeeded" >> $LOG_PATH
    fi
    go build -o swebapp .
    if [ -z $? ]; then
      echo "Go Build Succeeded" >> $LOG_PATH
    fi
}

function runApp {
    echo "Running scripts" >> $LOG_PATH
    pm2 stop swebapp >> $LOG_PATH
    pm2 start --name swebapp $BIN_PATH >> $LOG_PATH
    pm2 save >> $LOG_PATH
}

echo $BIN_PATH >> $LOG_PATH

BuildApp
runApp