#!/bin/sh

BIN_PATH=/home/ec2-user/swebapp/swebapp
TIME=`date -u`
LOG_PATH=/home/ec2-user/swebapp/swebapp-$TIME.log

# pm2 delete simple-app || : && pm2 start --name swebapp $BIN_PATH
echo "Building Application" >> $LOG_PATH
go mod tidy >> $LOG_PATH
go build -o swebapp >> $LOG_PATH

echo "Running scripts" >> $LOG_PATH
pm2 stop swebapp >> $LOG_PATH
pm2 start --name swebapp $BIN_PATH >> $LOG_PATH
pm2 save >> $LOG_PATH