# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run Tests
        run: go test -v .

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Application
        run: go build -v -o swebapp .

      - name: Copy Binary to EC2
        uses: appleboy/scp-action@master
        env:
          AWS_HOST: ec2-18-181-222-25.ap-northeast-1.compute.amazonaws.com
          AWS_USERNAME: ec2-user
          APP_TARGET: /home/ec2-user/app
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "./swebapp"
          target: ${{ env.APP_TARGET }}

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1

      # - name: Create CodeDeploy Deployment
      #   id: deploy
      #   run: |
      #     aws deploy create-deployment \
      #       --application-name automation-test-app \
      #       --deployment-group-name automation-test-group \
      #       --deployment-config-name CodeDeployDefault.OneAtATime \
      #       --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
